BEGIN;


-- Pour aider les Windows Users ;-) 
SET client_encoding TO 'UTF8';

DROP TABLE IF EXISTS "dessins", "artiste", "user", "role", "category_oeuvre", "oeuvre";

CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "firstname" VARCHAR(100) NOT NULL,
  "lastname" VARCHAR(100) NOT NULL,
  "email" VARCHAR(100) NOT NULL,
  "password" TEXT UNIQUE,
  "role_id" integer NOT NULL REFERENCES "role"("id"),
  "created_at" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "role" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(100) NOT NULL,
  "created_at" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "category_oeuvre" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(100) NOT NULL,
  "created_at" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "oeuvre" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "title" VARCHAR(100) NOT NULL UNIQUE,
  "id_number" INTEGER UNIQUE,
  "subject" TEXT NOT NULL,
  "realise_at" TIMESTAMPTZ,
  "size" TEXT NOT NULL,
  "signed" BOOLEAN NOT NULL,
  "url_picture" TEXT NOT NULL UNIQUE,
  "category_id" integer NOT NULL REFERENCES "category_oeuvre"("id"),
  "author_id" integer NOT NULL REFERENCES "user"("id"),
  "created_at" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

COMMIT;







