BEGIN;

SET client_encoding TO 'UTF8';

TRUNCATE TABLE "user", "role", "category_oeuvre", "oeuvre"; RESTART IDENTITY;
-- TRUNCATE supprime TOUS les enregistrements de la table, sans pour autant supprimer les tables elles-même.

INSERT INTO "user" ("firstname", "lastname", "email", "role_id") 
VALUES 
('lefebvre','Daniel', 'gregoirelefebvredelanghe@yahoo.fr', 2);
('lefebvre','Gregoire', 'gregoirelefebvredelanghe@yahoo.fr', 1);
('smith','jhon', 'lefebvredelanghegregoire@yahoo.fr', 2);


INSERT INTO "role" ("name") 
VALUES 
('administrateur');
('artiste');
('Utilisateur');



INSERT INTO "category_oeuvre" ("name") 
VALUES 
('dessin');
('planche de dessin');
('BD');
('tableaux');
('sculpture');










CREATE TABLE "category_oeuvre" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(100) NOT NULL,
  "created_at" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);










INSERT INTO "dessins" ("titre", "reference", "date_realisation", "format", "signature", "img_url", "artiste_id") 
VALUES 
('Micket et yoda', NULL, NULL, '24x32', TRUE, 'public/img/Micket et yoda.jpg', 1);
('Journée de la gentillesse', 'Attentats Paris 13 Nov 2015', '2015-11-14', '24x32', TRUE, 'public/img/Journée de la gentillesse.jpg', 1);
('Républic', `etat d'urgence +cop21`, '2015-12-01', '21x29', TRUE, 'public/img/Républic.jpg', 1);
('Goodyear', 'procès goodyears avec condamnations 01/2016', '2016-01-22', '24x32', TRUE, 'public/img/Journée de la gentillesse.jpg', 1);
(`C'est le prinptemps`, 'élections départementales 2015', '2015-03-20', '24x32', TRUE, 'public/img/Journée de la gentillesse.jpg', 1);
('Fashion week', 'fashion week + cop21', '2015-12-12', '24x32', TRUE, 'public/img/Journée de la gentillesse.jpg', 1);
('Tourisme shebab', 'attaque Kenia 147 mort', '2015-04-02', '24x32', TRUE, 'public/img/Journée de la gentillesse.jpg', 1);
(`L'air du temps`, `Réforme de l'orthographe`, '2016-03-20', '24x32', TRUE, 'public/img/Journée de la gentillesse.jpg', 1);
('Le Carillon', 'Attentat de Paris', '2015-11-23', '21x29', TRUE, 'public/img/Journée de la gentillesse.jpg', 1);
('Germanwings', 'accident German airwings', NULL, '24x32', TRUE, 'public/img/Journée de la gentillesse.jpg', 1);



















COMMIT; 